docs = [
    "Company Policy: Refunds are processed within 5–7 business days. A valid order ID must be provided. Refunds are issued to the original payment method only.",
    "Product Manual – SmartX Headphones: Press and hold the power button for 3 seconds until the LED flashes blue to enter pairing mode.",
    "Shipping Policy: Orders placed before 3 PM are dispatched the same day. Expected delivery is 3–5 working days.",
    "Troubleshooting: If the device does not turn on, hold the power button for 10 seconds to force reboot.",
    "Warranty: All electronic devices come with a 1-year manufacturer warranty covering internal hardware defects.",
    "User Guide – SmartHome App: To add a device, tap 'Add Device', select the category, and follow the on-screen steps.",
    "Return Policy: Products can be returned within 10 days if unused and in original packaging.",
    "Security Guidelines: Never share your password or OTP. Support teams never request sensitive login data.",
    "Membership Plan: Premium members get free shipping, priority support, and exclusive offers.",
    "FAQ – Connectivity: Restart your router, forget the network, and reconnect if Wi-Fi disconnects frequently.",
    "Device Reset Guide: To reset the device, hold the power button for 15 seconds until the LED turns red.",
    "Installation Manual – AirPurifier X1: Insert the filter, plug in the device, and press the start button for 2 seconds.",
    "Battery Instructions: Charge the device for at least 1 hour before first use for optimal battery performance.",
    "Privacy Policy Overview: User data is encrypted and never shared without explicit consent.",
    "Chatbot Support: For order status, users must provide their registered mobile number or order ID.",
    "Product Manual – SmartWatch Z: Swipe down to open quick settings and long-press to customize watch faces.",
    "Live Chat Guidelines: Agents should respond within 30 seconds and maintain a polite tone.",
    "Order Cancellation Rules: Orders can be canceled before they are shipped. After dispatch, cancellation is not possible.",
    "Firmware Update Notes: Ensure at least 50% battery before installing updates to avoid interruptions.",
    "Gift Card Policy: Gift cards are non-refundable and valid for 12 months from the date of issue.",
    "Technical Specs – Router R200: Supports 2.4 GHz band, maximum speed 300 Mbps, coverage up to 50 meters.",
    "HR Policy: Employees may take 12 annual leaves per year, credited monthly.",
    "Helpdesk Workflow: Tickets must be acknowledged within 1 hour and resolved within 24 hours.",
    "Anti-Spam Rule: Marketing emails are sent only to users who have opted-in.",
    "E-commerce Size Guide: Always refer to the size chart before ordering apparel items.",
    "Packaging Standards: Fragile products must be packed with double-layer bubble wrap.",
    "SLA Document: Uptime commitment is 99.5% per month excluding scheduled maintenance.",
    "Invoice Guide: All invoices include GST details and transaction ID.",
    "Product Manual – SmartBulb LITE: To reset, toggle the power switch 5 times rapidly.",
    "Complaint Redressal Policy: All complaints are resolved within 48–72 working hours.",
    "API Usage Policy: API calls exceeding 1000/day require an upgraded plan.",
    "Messenger Bot Guidelines: The bot must always confirm before executing destructive actions.",
    "QR Code Login Guide: Scan the code using the mobile app to instantly sign in.",
    "Internal Communication Rule: All announcements must be shared through the official communication portal.",
    "Customer Support Hours: Support is available from 9 AM to 9 PM, Monday to Saturday.",
    "Data Backup Policy: Automatic backups occur every 24 hours and are retained for 30 days.",
    "Subscription Cancellation: Users can cancel anytime; benefits continue until the current cycle ends.",
    "Maintenance Instructions – VacuumCleaner V10: Clean the dust bin after every use to maintain suction power.",
    "Password Policy: Minimum 8 characters, including one symbol and one number.",
    "Mobile App Permissions: Location access is required only during device pairing.",
    "API Authentication: All requests must include a valid bearer token.",
    "Employee Onboarding: New hires must complete digital onboarding within the first week.",
    "Refund Exception: Digital products are not eligible for refunds once downloaded.",
    "Support Escalation: Issues unresolved for 24 hours are auto-escalated to Level-2 engineers.",
    "Safety Instructions – PowerBank P20: Do not leave the device charging overnight.",
    "Resource Access Policy: Only authorized users can access internal dashboards.",
    "E-Warranty Registration: Customers must upload the purchase invoice within 30 days.",
    "Troubleshooting – App Crash: Clear cache, update the app, and restart the device.",
    "SMS Notification Policy: Users receive SMS updates only for critical account alerts.",
    "Device Pairing Help: Keep the device within 5 meters of your phone during pairing."
]
